### ISSUE TITLE
バグ

### ISSUE THREAD

**Issue by ShoWatanab** [miraikeitai2022/2022_1104_Github_hands-on#7]
Button("ワードクラウド >") {
                            self.showingSheet.toggle()
                            Firestore.firestore().collection("test").document(UIDevice.current.identifierForVendor!.uuidString).setData(self.speechRecorder.audioText)
                        }
動かない

**Comment by Satoshi1020015** [comment]
自分の環境では動いたよ
#2

**Comment by ShoWatanab** [comment]
嘘つけ
